### ISSUE TITLE
Missing Data!

### ISSUE THREAD

**Issue by tnbKristi** [tnbKristi/eorzea_timers#2]
I need more data for:
- Fishing Nodes
- Ephemeral Nodes
- Crazy high end need special access nodes

**Bonus:** I'd also like to collect the collectability rating for items, and whether they qualify for red/blue scrip.

**Comment by kiaka010** [comment]
I have found that that http://en.ff14angler.com/ has some good data and community in regards to times,bait,weather

Not to mention http://www.garlandtools.org/ which has information that has been data mined so should (hopefuly) be accurate

**Comment by tnbKristi** [comment]
Thank you @kiaka010 :+1:

**Comment by kiaka010** [comment]
@tnbKristi no problem :smile: 
Great site, looking forward to anything you have planned for the site.
If you need anything just shout :grinning:

**Comment by tnbKristi** [comment]
Thank you, much appreciated!! If you have any ideas please drop them in github issues somewhere. :)

**Comment by kiaka010** [comment]
@tnbKristi will do (i'll try not to give you too much work to do :worried: )

**Comment by tnbKristi** [comment]
Okay, I'm pretty happy with where the data is at now. We have support and filtering for all known ephemeral and legendary nodes (I just got my first legendary book tonight, wheee!)

**Comment by kiaka010** [comment]
Nice!
i'm working on my 3rd set of blue scrips (haven't even used any to get the books yet though so don't have any data from them, and my gathering is only un melded hq 60 gear so no where near the requirements for them yet)

Just remembered that there are also items from Favors

**Comment by tnbKristi** [comment]
Oh, right, favors - will re-open for that. Thanks for the reminder. :+1:

**Comment by kiaka010** [comment]
some of the nodes are active for 55 min, not the full hour (some collectable nodes from what i can remember). is that something to handle or round up?

**Comment by tnbKristi** [comment]
Nope that's not a problem, all the nodes that are 55 mins are in the data as such, the timer will support any arbitrary number the way it's built.

**Comment by tnbKristi** [comment]
Just dug into favors - they do not actually have an activation time based on Eorzean, it's purely just a self-buff that RNG activates those nodes in a given zone. So because of that I don't think it belongs in the timer data. 

Thanks!

**Comment by kiaka010** [comment]
ahhhh good point. ignore me lol
