### ISSUE TITLE
Clear all doesnt remove selected list

### ISSUE THREAD

**Issue by kiaka010** [tnbKristi/eorzea_timers#25]
When using the clear all button the blue selection bar isnt removed from the home list

Steps to reproduce
1) select a node to watch
2) go to Watch Tab
3) click clear all
4) go to home tab
5) node still selected

Doesn't look like its being cleared from the local storage

Also (very minor) between 3 and 4 the Watch tab count doesn't reset on clicking clear all but does when clicking home

**Comment by tnbKristi** [comment]
Yeah, it's also not saving the new empty state. I'll have a patch up soon. :(
