### ISSUE TITLE
Alerts not working

### ISSUE THREAD

**Issue by kiaka010** [tnbKristi/eorzea_timers#26]
I was able to get a desktop notification once
and nothing since. No sound or browser alerts

.... ive no idea what i did to break it

**Comment by tnbKristi** [comment]
What browser are you using? I only tested in Chrome so far.

**Comment by kiaka010** [comment]
Mac Chrome

**Comment by kiaka010** [comment]
oh might have worked it out. i was able to get a desktop notification for a node in a hour but wasnt able to get one starting now

**Comment by tnbKristi** [comment]
ooh, interesting. I'll check that out. Admittedly I spent more time testing the 1 hour ahead notification as that's what I prefer, lol

**Comment by kiaka010** [comment]
hahaha

**Comment by kiaka010** [comment]
(ooops wrong button)

**Comment by tnbKristi** [comment]
was definitely a 0 hours notification issue - should be good now.
