### ISSUE TITLE
Console error on playing allert sound and moving to a new tab before its finished

### ISSUE THREAD

**Issue by kiaka010** [tnbKristi/eorzea_timers#30]
Steps to reproduce: (console log needs to be open the whole time)
1) to go watch tab
2) open preferences
3) select a sound alert (if one is already selected then the play button is not there. maybe a bug) (big ben goes on a while so might be the best option
4) in quick succession. Press Play -> save/close preferences -> to to another tab
5) notice error in console log

Error:
Uncaught TypeError: this.ui.soundSelect.val is not a functionViews.Preferences.Marionette.LayoutView.extend.toggleSound @ app.js:607
Entities.Sound.Backbone.Model.extend.play.soundManager.play.onfinish @ app.js:1580
(anonymous function) @ lib.js:36101
wrapCallback @ lib.js:3639
0oOptions._onfinish @ lib.js:36100
(anonymous function) @ lib.js:36734
(anonymous function) @ lib.js:36633

might not be anything serious

**Comment by tnbKristi** [comment]
Haha thats a good one, gratefully super-easy to fix.
