### ISSUE TITLE
Customer timer might need a character limit

### ISSUE THREAD

**Issue by kiaka010** [tnbKristi/eorzea_timers#34]
Be the users fault for doing this but

Steps to reproduce
1) create a 12AM timer where the location/name text is very long
2) add timer to watch list)
3) add about 4 timers after 12AM
4) to to watch tab
![screen shot 2015-10-09 at 15 46 33](https://cloud.githubusercontent.com/assets/12197015/10397001/51d04564-6e9d-11e5-8fb7-f6a174dec088.png)
![screen shot 2015-10-09 at 15 46 24](https://cloud.githubusercontent.com/assets/12197015/10397004/53f060d6-6e9d-11e5-83cb-0826cd5dbfa3.png)
![screen shot 2015-10-09 at 15 47 38](https://cloud.githubusercontent.com/assets/12197015/10397008/56288a90-6e9d-11e5-8ed4-998eb8dcdb02.png)

**Comment by tnbKristi** [comment]
lmao :+1:

**Comment by kiaka010** [comment]
also works is the word has no spaces
![screen shot 2015-10-09 at 16 30 17](https://cloud.githubusercontent.com/assets/12197015/10398096/0d9afc76-6ea3-11e5-8d33-4186c7191e74.png)
