### ISSUE TITLE
Nodes removed from Watch List are still highlighted in All Nodes list

### ISSUE THREAD

**Issue by kiaka010** [tnbKristi/eorzea_timers#5]
When a node is selected to watch and is then removed though the "Watch List" section the node is is still selected (blue) in the Home All list

Then requires to be clicked 3 times before it is not longer highlighted (once if node is active and already highlighted)

Steps to Reproduce
1) select node up next (filter: all)
2) go to Watch List
3) remove node from watch list
4) go to Home
5) Node original selected and removed is still selected
6) click 3 times to remove blue selection bar (once for active node with red or amber background)

JS error in console
app.js:63 Uncaught TypeError: Cannot read property 'destroy' of undefined
(anonymous function)	@	app.js:63
triggerEvents	@	lib.js:14716
triggerApi	@	lib.js:14703
eventsApi	@	lib.js:14502
Events.trigger	@	lib.js:14693
Views.NodeView.Marionette.ItemView.extend.toggleSelect	@	app.js:415
jQuery.event.dispatch	@	lib.js:4435
elemData.handle	@	lib.js:4121
.

**Comment by tnbKristi** [comment]
Ooo, that's a good one. Confirmed and reproduced on my side, will patch a fix. Thanks!

**Comment by kiaka010** [comment]
@tnbKristi no probs (sorry if i start to annoy you lol)
